#!/bin/bash
#
#    Syntaxe : sbatch $0 [options] Config_filename
#               ==============================================================================
#               Config_filename = file on which inputs (namelists,executables,data) are defined
#                                 for those which are not defined a default value is use instead
#                                 if not provided, defaults are used 
#               ==============================================================================
#               -p  0 -> no pgd computed
#                   1 -> pgd computed (default)
#               ==============================================================================
#
#
#
#SBATCH -p shared
#SBATCH --ntasks 1
#SBATCH --time=02:00:00
#SBATCH -J pgd-prep_climat
#SBATCH -o pgd-prep_climat.o%j
#
set -x
#
LPGD=1
OPTIND='1'
while getopts :p: V ; do
  case $V in 
    (p) LPGD=${OPTARG} ;;
  esac
done
#
shift $(($OPTIND-1));
CONFIGFILE=$1
expname=cy49t1_clim1.03_tl127r
if [ -s "$CONFIGFILE" ] ; then
  source $CONFIGFILE
  expname=$(basename $CONFIGFILE)
fi
#
#=========================================================================
#===== Default Configuration
#=========================================================================
#
# assuming the job has been lauch from the toolbox-arpege/pgd-prep directory
TOOLBOX_DIR=$(pwd)/..
#=== Is TRIP involved (default 0=no)
LTRIP=${LTRIP:-0}
#
#=== Binaries
EXEPGD=${EXEPGD:-/scratch/climat/packs/CY49T1_clim1.03.IMPIIFC2302DP.y/bin/PGD}
EXEPREP=${EXEPREP:-/scratch/climat/packs/CY49T1_clim1.03.IMPIIFC2302DP.y/bin/PREP}
EXETRIP=${EXETRIP:-/scratch/climat/packs/CY49T1_clim1.03.IMPIIFC2302DP.y/bin/TRIP_PREP}

#=== Namelists
SFXNAM=${SFXNAM:-${TOOLBOX_DIR}/namelist/sfx/nam.sfx.tl127r.pgd.cy49t1_clim1.03}
TRIPNAML=${TRIPNAML:-${TOOLBOX_DIR}/namelist/riv/nam.riv.05deg.prep.cy49t1_clim1.03}
OASISNAML=${OASISNAML:-${TOOLBOX_DIR}/namelist/cpl/namcouple.prep} # Empty namelist, just needed for OASIS

#=== Restarts
FA_PGDFILE=${FA_PGDFILE:-/scratch/climat/CEDRE/restart/sfx/tl127r/v7/PGD.AGCM.tl127r.cy49t1_clim1.03.fa}
FA_INITFILE=${FA_INITFILE:-/scratch/climat/CEDRE/restart/sfx/tl127r/v7/rst.sfx.AGCM.tl127r.cy49t1_clim1.03.19790101.fa}
TRIP_INITFILE=${TRIP_INITFILE:-/scratch/climat/CEDRE/restart/riv/riv05/v7/rst.trp.AGCM.riv05.nc}

#=== Output directory
SAVEDIR=${SAVEDIR:-$workdir/surfex/pgdprep/$expname}

#=== Constants files and directory sources
ECODIR=${ECODIR:-/scratch/climat/CMIP6/data/sfx}
SFX9DIR=${SFX9DIR:-/scratch/climat/CEDRE/data/sfx/miscellaneaous/v7}
FRACDIR=$FRACDIR # frac_*.asc - not used for the moment
TRIPDIR=${TRIPDIR:-/scratch/climat/CEDRE/data/riv/riv05_v7}

#=========================================================================
#===== End of main configuration elements
#=========================================================================
#
if [ ! -r $SAVEDIR ]; then
  mkdir -p $SAVEDIR
fi
[ $LPGD -eq 1 ] && rm -f $SAVEDIR/*

#=== Environement
ulimit -s unlimited
module purge
module load intel/oneapi/2023.2 compiler/2023.2.0 mkl/2023.2.0 mpi/2021.10.0 gcc/14.1.0 2>/dev/null

export DR_HOOK=0
export DR_HOOK_IGNORE_SIGNALS=-1
export DR_HOOK_SILENT=1
export DR_HOOK_OPT=prof
export DR_HOOK_NOT_MPI=1
export MPL_MBX_SIZE=2048000000
export EC_PROFILE_HEAP=0
export EC_MPI_ATEXIT=0
export OMP_NUM_THREADS=1

# must have this to run PGD with CY49
export DR_HOOK_ASSERT_MPI_INITIALIZED=0

#=========================================================================
#===== Preparation of execution
#=========================================================================

#=== TRIP data
if [[ $LTRIP -ne 0 ]] ; then
   mkdir -p $SAVEDIR/data_trip
   mkdir -p $SAVEDIR/data_oasis
fi

#=== Run directory
TEMPORAIRE=$TMPDIR
cd $TEMPORAIRE

#=== Copying Namelist
echo " copie de la namelist surfex"
cp $SFXNAM OPTIONS.nam
if [[ $LTRIP -ne 0 ]] ; then
   echo " "
   echo " copie de la namelist trip"
   cp $TRIPNAML TRIP_OPTIONS.nam
   cp $OASISNAML namcouple
fi

#=== Copying constant
ln -s $ECODIR/ecoclimapI_covers_param.bin .
ln -s $ECODIR/ecoclimapII_eu_covers_param.bin .


#=========================================================================
#===== PGD execution 
#=========================================================================

if [[ $LPGD -ne 0 ]] ; then
   echo " !!!!!!!!!! PGD CASE !!!!!!!! "
   echo " copie des fichiers ecoclimap "

   #=== Copying constant
   ln -s $ECODIR/gmted1km.dir topo.dir
   ln -s $ECODIR/gmted1km.hdr topo.hdr

   ln -s $SFX9DIR/ga2_topo_index.dir topo_index.dir
   ln -s $SFX9DIR/ga2_topo_index.hdr topo_index.hdr

   ln -s $ECODIR/ECOCLIMAP_II_EUROP_V2.4.dir ecoclimap.dir
   ln -s $ECODIR/ECOCLIMAP_II_EUROP_V2.4.hdr ecoclimap.hdr

   ln -s $ECODIR/LAKE_DEPTH_ECO_II_V2.4.dir lake_depth.dir
   ln -s $ECODIR/LAKE_DEPTH_ECO_II_V2.4.hdr lake_depth.hdr

   ln -s $ECODIR/CLAY_HWSD_MOY_v2.dir clay.dir
   ln -s $ECODIR/CLAY_HWSD_MOY_v2.hdr clay.hdr
   ln -s $ECODIR/SAND_HWSD_MOY_v2.dir sand.dir
   ln -s $ECODIR/SAND_HWSD_MOY_v2.hdr sand.hdr

   ln -s $ECODIR/soc* .
   ln -s $ECODIR/perm_glo* .

   # nat/sea/wat fraction files to follow nemo land/sea mask - if not used in the namelist and not present here -> no pb
   ln -s  $FRACDIR/frac_???.asc .

   #for vegtype in `seq 1 1 19` ; do
   #  [ ${LUYEAR} -gt 0 ] && ln -s ${LULUCCF}/vegtype${vegtype}_1d_60S-90N_cmip6_official_LUH2_GCP2023_lulccf_on_ecoclimap_${LUYEAR}.txt pft${vegtype}.txt
   #done

   echo " copie et execution du pgd "
   ln -s $EXEPGD pgd.exe
   ./pgd.exe

   #=== Error catching
   if [[ $? -ne 0 ]] ; then
      echo "run pgd failed !!! See in directory: $TEMPORAIRE"
      cat LISTING_PGD.txt
      cat OPTIONS.nam
      exit
   fi

   #=== Saving outputs
   mv PGD.fa  $SAVEDIR/PGD.fa
   #mv PGD.nc  $SAVEDIR/PGD.nc

  if [[ $DR_HOOK -ne 0 ]] ; then
     mv drhook.prof.1 $SAVEDIR/drhook.prof_pgd
     mv LISTING_PGD.txt $SAVEDIR/LISTING_PGD.txt
  fi

fi


#=========================================================================
#=== PREP execution - with or without TRIP
#=========================================================================

echo " !!!!!!!!!! PREP CASE !!!!!!!! "

#=== TRIP option
if [[ $LTRIP -ne 0 ]] ; then
   ln -s $TRIPDIR/TRIP_PGD_HD.nc .
   ln -s $TRIPDIR/TRIP_SGAQUI_HD.nc .
   ln -s $TRIPDIR/TRIP_SGFLOOD_HD.nc .
   ln -s $TRIP_INITFILE TRIP_INIT_HD.nc
   
   ln -s $EXETRIP trip_prep.exe
fi

#=== Copying restart and PGD
ln -s $FA_PGDFILE restart_sfx_pgd.fa
ln -s $FA_INITFILE restart_sfx.fa

ln -s $SAVEDIR/PGD.fa PGD.fa

echo " copie et execution du prep "
ln -s $EXEPREP prep.exe
if [[ $LTRIP -ne 0 ]] ; then
   mpirun -np 1 prep.exe : -np 1 trip_prep.exe
else
   ./prep.exe
fi

#=== Error catching
if [[ $? -ne 0 ]] ; then
  echo "run prep failed !!! See in directory: ${TEMPORAIRE}"
  cat LISTING_PREP0.txt
  exit
fi

#=== Saving output
mv PREP.fa  $SAVEDIR/.

if [[ $LTRIP -ne 0 ]] ; then
   mv TRIP_PREP.nc $SAVEDIR/.
   mv TRIP_PARAM.nc $SAVEDIR/data_trip/.
   mv areas.nc $SAVEDIR/data_oasis/.
   mv grids.nc $SAVEDIR/data_oasis/.
   mv masks.nc $SAVEDIR/data_oasis/.
fi

if [[ $DR_HOOK -ne 0 ]] ; then
   mv drhook.prof.1 $SAVEDIR/drhook.prof_prep
   mv LISTING_PREP.txt $SAVEDIR/LISTING_PREP.txt
fi


#=========================================================================
#===== Cleaning and exit
#=========================================================================
exit

