#!/bin/bash
#
#    Syntaxe : sbatch $0 [options] 
#               ==============================================================================
#               -p  0 -> no pgd computed
#                   1 -> pgd computed (default)
#               ==============================================================================
#               -c  Config_filename
#               Config_filename = file on which inputs (namelists,executables,data) are defined
#                                 for those which are not defined a default value is use instead
#                                 if not provided, defaults are used
#               ==============================================================================
#
#
#
#SBATCH -p shared
#SBATCH --ntasks 1
#SBATCH --time=02:00:00
#SBATCH -J pgd-prep_climat
#SBATCH -o pgd-prep_climat.o%j
#SBATCH --mem=8Gb
#
set -x
#
OPTIND='1'
while getopts "p:c:h?" flags ; do
  case $flags in 
    p) LPGD=${OPTARG} ;;
    c) CONFIGFILE=${OPTARG} ;;
    h|?) echo -e "job_pgd_prep takes two optional kwargs :\n -c config file \n -p option to create pgd  "
         exit 0;;
    \?) echo "Invalid argument "${flags[@]:$OPTIND:1} 
        exit 1;;
  esac
done
#
shift $(($OPTIND-1));

if [ $# -ne 0 ]; then
  echo "Invalid argument(s) "$@
  exit 1
fi

expname=cy49t1_clim1.03_tl127r
if [ -s "$CONFIGFILE" ] ; then
  CONFIGFILE=$( realpath $CONFIGFILE )
  expname=$(basename $CONFIGFILE)
  source $CONFIGFILE
fi
#
#=========================================================================
#===== Default Configuration
#=========================================================================
#
# Create PGD by default
LPGD=${LPGD:-1}
#
# assuming the job has been lauch from the toolbox-arpege/pgd-prep directory
TOOLBOX_DIR=$(pwd)/..
#=== Is TRIP involved (default 0=no)
LTRIP=${LTRIP:-0}
#
#=== Binaries
EXEPGD=${EXEPGD:-/scratch/climat/packs/CY49T1_clim1.03.IMPIIFC2302DP.y/bin/PGD}
EXEPREP=${EXEPREP:-/scratch/climat/packs/CY49T1_clim1.03.IMPIIFC2302DP.y/bin/PREP}
EXETRIP=$EXETRIP

#=== Namelists
NAMSFX=${NAMSFXpgd:-${TOOLBOX_DIR}/namelist/sfx/nam.sfx.tl127r.pgd.cy49t1_clim1.03}
TRIPNAML=${TRIPNAML}
OASISNAML=${OASISNAML:-${TOOLBOX_DIR}/namelist/cpl/namcouple.prep} # Empty namelist, just needed for OASIS

#=== Restarts
FA_PGDFILE=${FA_PGDFILE:-/scratch/climat/CEDRE/restart/sfx/tl127r/v7/PGD.AGCM.tl127r.cy49t1_clim1.03.fa}
FA_INITFILE=${FA_INITFILE:-/scratch/climat/CEDRE/restart/sfx/tl127r/v7/rst.sfx.AGCM.tl127r.cy49t1_clim1.03.19790101.fa}
TRIP_INITFILE=$TRIP_INITFILE

#=== Output directory
SAVEDIR=${SAVEDIR:-$workdir} ; SAVEDIR=$SAVEDIR/pgdprep/$expname

#=== Constants files and directory sources
ECODIR=${ECODIR:-/home/cnrm_other/ge/mrmm/decharme/ecoclimap_cnrm_cm6.02}
FRACDIR=${FRACDIR:-/scratch/work/roehrig/sfx/ecoclimap/46t1} # for frac_*.asc
TRIPDIR=${TRIPDIR:-$ECODIR}
GRIB_INITFILE=$ECODIR/restart_grib/GRIDSURFARP.tl127l31r

#=== Files for PGD
LFILEScst="${ECODIR}/ecoclimapI_covers_param.bin:ecoclimapI_covers_param.bin ${ECODIR}/ecoclimapII_eu_covers_param.bin:ecoclimapII_eu_covers_param.bin"
LFILES="${ECODIR}/gmted1km.dir:topo.dir ${ECODIR}/gmted1km.hdr:topo.hdr"
LFILES+=" /home/gmgec/mrgu/hardouinl/ga2_ti/ga2_topo_index.dir:topo_index.dir /home/gmgec/mrgu/hardouinl/ga2_ti/ga2_topo_index.hdr:topo_index.hdr"
LFILES+=" ${ECODIR}/ECOCLIMAP_II_EUROP_V2.4.dir:ecoclimap.dir ${ECODIR}/ECOCLIMAP_II_EUROP_V2.4.hdr:ecoclimap.hdr"
LFILES+=" ${ECODIR}/LAKE_DEPTH_ECO_II_V2.4.dir:lake_depth.dir ${ECODIR}/LAKE_DEPTH_ECO_II_V2.4.hdr:lake_depth.hdr"
LFILES+=" ${ECODIR}/CLAY_HWSD_MOY_v2.dir:clay.dir ${ECODIR}/CLAY_HWSD_MOY_v2.hdr:clay.hdr"
LFILES+=" ${ECODIR}/SAND_HWSD_MOY_v2.dir:sand.dir ${ECODIR}/SAND_HWSD_MOY_v2.hdr:sand.hdr"
LFILES+=" ${ECODIR}/soc_sub.dir:soc_sub.dir ${ECODIR}/soc_sub.hdr:soc_sub.hdr ${ECODIR}/soc_top.dir:soc_top.dir ${ECODIR}/soc_top.hdr:soc_top.hdr"
LFILES+=" ${ECODIR}/perm_glo_10km.dir:perm_glo_10km.dir ${ECODIR}/perm_glo_10km.hdr:perm_glo_10km.hdr"

ECOFILEScst=${ECOFILEScst:-$LFILEScst}
ECOFILES=${ECOFILES:-$LFILES}

#=========================================================================
#===== End of main configuration elements
#=========================================================================
#
if [ ! -r $SAVEDIR ]; then
  mkdir -p $SAVEDIR
fi
[ $LPGD -eq 1 ] && rm -f $SAVEDIR/P*.fa

#=== Environement
ulimit -s unlimited
module purge
module load intel/oneapi/2023.2 compiler/2023.2.0 mkl/2023.2.0 mpi/2021.10.0 gcc/14.1.0 2>/dev/null

export DR_HOOK=0
export DR_HOOK_IGNORE_SIGNALS=-1
export DR_HOOK_SILENT=1
export DR_HOOK_OPT=prof
export DR_HOOK_NOT_MPI=1
export MPL_MBX_SIZE=2048000000
export EC_PROFILE_HEAP=0
export EC_MPI_ATEXIT=0
export OMP_NUM_THREADS=1

# must have this to run PGD with CY49
export DR_HOOK_ASSERT_MPI_INITIALIZED=0

#=========================================================================
#===== Preparation of execution
#=========================================================================

#=== TRIP data
if [[ $LTRIP -ne 0 ]] ; then
   mkdir -p $SAVEDIR/data_trip
   mkdir -p $SAVEDIR/data_oasis
fi

#=== Run directory
TEMPORAIRE=$TMPDIR
cd $TEMPORAIRE

#=== Copying Namelist
echo " copie de la namelist surfex"
cp $NAMSFX OPTIONS.nam
if [[ $LTRIP -ne 0 ]] ; then
   echo " "
   echo " copie de la namelist trip"
   cp $TRIPNAML TRIP_OPTIONS.nam
   cp $OASISNAML namcouple
fi

#=== Copying constant
for files in ${ECOFILEScst} ; do
  forig=${files%:*} ; ftarg=${files#*:}
  ln -s $forig $ftarg
done


#=========================================================================
#===== PGD execution 
#=========================================================================

if [[ $LPGD -ne 0 ]] ; then
   echo " !!!!!!!!!! PGD CASE !!!!!!!! "
   echo " copie des fichiers ecoclimap "

   for files in ${ECOFILES} ; do
       forig=${files%:*} ; ftarg=${files#*:}
       ln -s $forig $ftarg
   done

   # nat/sea/wat fraction files to follow nemo land/sea mask - if not used in the namelist and not present here -> no pb
   ln -s  $FRACDIR/frac_???.asc .

   #for vegtype in `seq 1 1 19` ; do
   #  [ ${LUYEAR} -gt 0 ] && ln -s ${LULUCCF}/vegtype${vegtype}_1d_60S-90N_cmip6_official_LUH2_GCP2023_lulccf_on_ecoclimap_${LUYEAR}.txt pft${vegtype}.txt
   #done

   echo " copie et execution du pgd "
   ln -s $EXEPGD pgd.exe
   ./pgd.exe

   #=== Error catching
   if [[ $? -ne 0 ]] ; then
      echo "run pgd failed !!! See in directory: $TEMPORAIRE"
      cat LISTING_PGD.txt
      cat OPTIONS.nam
      exit
   fi

   #=== Saving outputs
   mv PGD.fa  $SAVEDIR/PGD.fa
   echo "PGD=$SAVEDIR/PGD.fa">>$CONFIGFILE
   #mv PGD.nc  $SAVEDIR/PGD.nc

  if [[ $DR_HOOK -ne 0 ]] ; then
     mv drhook.prof.1 $SAVEDIR/drhook.prof_pgd
     mv LISTING_PGD.txt $SAVEDIR/LISTING_PGD.txt
  fi

fi


#=========================================================================
#=== PREP execution - with or without TRIP
#=========================================================================

echo " !!!!!!!!!! PREP CASE !!!!!!!! "

#=== TRIP option
if [[ $LTRIP -ne 0 ]] ; then
   ln -s $TRIPDIR/TRIP_PGD_HD.nc .
   ln -s $TRIPDIR/TRIP_SGAQUI_HD.nc .
   ln -s $TRIPDIR/TRIP_SGFLOOD_HD.nc .
   ln -s $TRIP_INITFILE TRIP_INIT_HD.nc
   
   ln -s $EXETRIP trip_prep.exe
fi

#=== Copying restart and PGD
ln -s $GRIB_INITFILE restart_atm
ln -s $FA_PGDFILE restart_sfx_pgd.fa
ln -s $FA_INITFILE restart_sfx.fa

ln -s $SAVEDIR/PGD.fa PGD.fa

echo " copie et execution du prep "
ln -s $EXEPREP prep.exe
if [[ $LTRIP -ne 0 ]] ; then
   mpirun -np 1 prep.exe : -np 1 trip_prep.exe
else
   ./prep.exe
fi

#=== Error catching
if [[ $? -ne 0 ]] ; then
  echo "run prep failed !!! See in directory: ${TEMPORAIRE}"
  #cat LISTING_PREP0.txt
  exit
fi

#=== Saving output
mv PREP.fa  $SAVEDIR/.

if [[ $LTRIP -ne 0 ]] ; then
   mv TRIP_PREP.nc $SAVEDIR/.
   mv TRIP_PARAM.nc $SAVEDIR/data_trip/.
   mv areas.nc $SAVEDIR/data_oasis/.
   mv grids.nc $SAVEDIR/data_oasis/.
   mv masks.nc $SAVEDIR/data_oasis/.
fi

if [[ $DR_HOOK -ne 0 ]] ; then
   mv drhook.prof.1 $SAVEDIR/drhook.prof_prep
   mv LISTING_PREP.txt $SAVEDIR/LISTING_PREP.txt
fi


#=========================================================================
#===== Cleaning and exit
#=========================================================================
exit

